-- 코드를 입력하세요
SELECT a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, sum(b.PRICE * bs.SALES) TOTAL_SALES
FROM BOOK b
LEFT JOIN AUTHOR a on b.AUTHOR_ID = a.AUTHOR_ID
LEFT JOIN BOOK_SALES bs on b.BOOK_ID = bs.BOOK_ID
WHERE bs.SALES_DATE LIKE "2022-01%"
GROUP BY a.AUTHOR_NAME, b.CATEGORY
ORDER BY b.AUTHOR_ID asc, b.CATEGORY desc;

